import java.util.Arrays;
import java.util.List;

public class DataGenerator {

    public static List getData(){
       return Arrays.asList("apple at 10p",
               "apple at 20p",
               "20 sales of orange at 10p each",
               "apple at 20p",
               "apple at 20p",
               "apple at 20p",
               "apple at 20p",
               "apple at 20p",
               "orange at 20p",
               "orange at 20p",
               "orange at 20p",
               "orange at 20p",
               "orange at 20p",
               "orange at 20p",
               "orange at 20p",
               "orange at 20p",
               "orange at 20p",
               "banana at 20p",
               "banana at 20p",
               "banana at 20p",
               "banana at 20p",
               "banana at 20p",
               "banana at 20p",
               "Fake Wrong message",
               "20 sales of orange at 10p each",
               "20 sales of banana at 20p each",
               "Add 20p apple",
               "Add 200p mango",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "multiply 4p banana",
               "substract 20p banana",
               "mango at 20p",
               "mango at 20p",
               "Add 20p banana",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p",
               "mango at 20p");
    }
}
